# Generated by Django 4.1.5 on 2023-01-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('event', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=50)),
            ],
        ),
    ]
