# Generated by Django 4.1.5 on 2023-01-31 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime),
        ),
    ]
